// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGJStNodFA4UxjcJuYYd5ltDMb8WnUeAM',
    appId: '1:539600706792:ios:8653099dbfdd6a343f7d5d',
    messagingSenderId: '539600706792',
    projectId: 'queuetrack-84755',
    storageBucket: 'queuetrack-84755.firebasestorage.app',
    iosBundleId: 'com.example.queuetrack',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFLxutDCPZ3oS_SJhEsd1_-svD8RDwH5Y',
    appId: '1:539600706792:web:203894d9cd0187ed3f7d5d',
    messagingSenderId: '539600706792',
    projectId: 'queuetrack-84755',
    authDomain: 'queuetrack-84755.firebaseapp.com',
    storageBucket: 'queuetrack-84755.firebasestorage.app',
    measurementId: 'G-P11G3HVEM2',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGJStNodFA4UxjcJuYYd5ltDMb8WnUeAM',
    appId: '1:539600706792:ios:8653099dbfdd6a343f7d5d',
    messagingSenderId: '539600706792',
    projectId: 'queuetrack-84755',
    storageBucket: 'queuetrack-84755.firebasestorage.app',
    iosBundleId: 'com.example.queuetrack',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALBXzg4FpbjzLQiN8BYX5k9sijsxa9p1s',
    appId: '1:539600706792:android:ed5154ab657e42143f7d5d',
    messagingSenderId: '539600706792',
    projectId: 'queuetrack-84755',
    storageBucket: 'queuetrack-84755.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFLxutDCPZ3oS_SJhEsd1_-svD8RDwH5Y',
    appId: '1:539600706792:web:59d3d188efc9576c3f7d5d',
    messagingSenderId: '539600706792',
    projectId: 'queuetrack-84755',
    authDomain: 'queuetrack-84755.firebaseapp.com',
    storageBucket: 'queuetrack-84755.firebasestorage.app',
    measurementId: 'G-R6RFGG25DH',
  );

}